name: "Feature Request"
description: Suggest new feature
title: "[FEATURE]:"
labels: ["enhancement"]

body:
  - type: checkbox
    attributes:
      label: I have verified this feature I'm about to request hasn't been suggested before.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the enhancement
      description: What do you want to change or add? What are the benefits of implementing this?
    validations:
      required: true
